
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocqbtiufmshozgegkabd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jcWJ0aXVmbXNob3pnZWdrYWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjA3MzksImV4cCI6MjA2MDQ5NjczOX0.DK9iU-mutB1YxmPPIM5j9VbS5Ekxv69h9A5Rq91LRY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
